version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    open-pull-requests-limit: 10
    reviewers:
      - 'mpont91'
    assignees:
      - 'mpont91'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    open-pull-requests-limit: 10
    reviewers:
      - 'mpont91'
    assignees:
      - 'mpont91'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
